export const UPDATE_INSTRUCTIONS = 'UPDATE_INSTRUCTIONS';
export const SANITIZE_INSTRUCTIONS = 'SANITIZE_INSTRUCTIONS';
export const GET_MATCHING_ANSWER = 'GET_MATCHING_ANSWER';
export const GET_FAVOURITES_MANGAS_SUCCESS = 'GET_FAVOURITES_MANGAS_SUCCESS';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const LAUNCH_PLAYLIST = 'LAUNCH_PLAYLIST';
